yarn create react-app react-graphql-ts --template typescript
cd react-graphql-ts

# Deps
yarn add @material-ui/core \
  @material-ui/icons \
  @apollo/client \
  graphql \
  react-router-dom
yarn add -D @graphql-codegen/cli \
  @graphql-codegen/introspection \
  @graphql-codegen/near-operation-file-preset \
  @graphql-codegen/typescript \
  @graphql-codegen/typescript-operations \
  @graphql-codegen/typescript-react-apollo \
  @types/react-router-dom \
  prettier

# Config codegen
cat > codegen.yml <<EOL
overwrite: true
schema: "http://localhost:8080/graphql"
documents: "src/graphql/*.graphql"
generates:
  src/graphql/generated/types.ts:
    - typescript
  src/graphql/generated/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.ts
      folder: generated
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHooks: true
  ./graphql.schema.json:
    plugins:
      - "introspection"
EOL

# Config prettier
cat > .prettierrc <<EOL
{
  "trailingComma": "all",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "jsxSingleQuote": true
}
EOL

cat > .prettierignore <<EOL
# Ignore artifacts:
build
coverage
src/graphql/generated

# Ignore files that were generated by create-react-app
src/index.tsx
src/serviceWorker.ts

# Ignore all HTML files:
*.html
EOL

cat > .editorconfig <<EOL
# http://editorconfig.org

# A special property that should be specified at the top of the file outside of
# any sections. Set to true to stop .editor config file search on current file
root = true

[*]
# Indentation style
# Possible values - tab, space
indent_style = space

# Indentation size in single-spaced characters
# Possible values - an integer, tab
indent_size = 2

# Line ending file format
# Possible values - lf, crlf, cr
end_of_line = lf

# File character encoding
# Possible values - latin1, utf-8, utf-16be, utf-16le
charset = utf-8

# Denotes whether to trim whitespace at the end of lines
# Possible values - true, false
trim_trailing_whitespace = true

# Denotes whether file should end with a newline
# Possible values - true, false
insert_final_newline = true
EOL

yarn prettier --write .